import { CmsCollection } from "netlify-cms-core";

export const projects: CmsCollection = {
  name: "projects",
  label: "Projects",
  label_singular: "Project",
  folder: "content/projects",
  create: true,
  format: "json",
  identifier_field: "slug",
  sortable_fields: ["created"],
  slug: "{{slug}}",
  media_folder: "/public/content/media/",
  public_folder: "/content/media/",
  fields: [
    {
      label: "Slug",
      name: "slug",
      widget: "string",
      required: true,
    },
    {
      label: "Title",
      name: "title",
      widget: "string",
      required: true,
    },
    {
      label: "Description",
      name: "description",
      widget: "string",
      required: true,
    },
    {
      label: "Tags",
      name: "tags",
      widget: "list",
      allow_add: true,
      required: true,
    },
    {
      label: "Created",
      name: "created",
      widget: "datetime",
      required: true,
    },
    {
      label: "Thumbnail",
      name: "thumbnail",
      widget: "image",
      required: true,
    },
    {
      label: "Links",
      name: "links",
      widget: "list",
      required: true,
      fields: [
        {
          label: "Label",
          name: "label",
          widget: "string",
          required: true,
        },
        {
          label: "URL",
          name: "url",
          widget: "string",
          required: true,
        },
      ],
    },
    {
      label: "Featured?",
      name: "featured",
      widget: "boolean",
      required: true,
    },
  ],
};

export const posts: CmsCollection = {
  name: "posts",
  label: "Posts",
  label_singular: "Post",
  folder: "content/posts",
  create: true,
  format: "yaml-frontmatter",
  extension: "mdx",
  identifier_field: "slug",
  sortable_fields: ["created"],
  slug: "{{slug}}",
  path: "{{year}}/{{slug}}",
  media_folder: "/public/content/media/",
  public_folder: "/content/media/",
  fields: [
    {
      label: "Slug",
      name: "slug",
      widget: "string",
      required: true,
    },
    {
      label: "Title",
      name: "title",
      widget: "string",
      required: true,
    },
    {
      label: "Description",
      name: "description",
      widget: "string",
      required: true,
    },
    {
      label: "Tags",
      name: "tags",
      widget: "list",
      allow_add: true,
      required: true,
    },
    {
      label: "Created",
      name: "created",
      widget: "datetime",
      required: true,
    },
    {
      label: "Updated",
      name: "updated",
      widget: "datetime",
      required: true,
    },
    {
      label: "Thumbnail",
      name: "thumbnail",
      widget: "image",
      required: true,
    },
    {
      label: "Body",
      name: "body",
      widget: "markdown",
      required: true,
    },
  ],
};
